# action - GitHub will build an image from your Dockerfile, and run commands in a new container using this image
# In order for GitHub to recognize output variables, you must write them to 
# the $GITHUB_OUTPUT environment file: echo "<output name>=<value>" >> $GITHUB_OUTPUT. 
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet: # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  what-country:
    description: 'what country you are'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
  runner:
    description: 'runner id'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.what-country }}