on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Michael Taquia'
          what-country: 'Peru'
      # Use the output from the `hello` step
      - name: Get the output runner and time
        run: echo "the runner was ${{ steps.hello.outputs.runner }} and the time was ${{ steps.hello.outputs.time }}"
